name: Deploy WA Gateway to VPS

on:
  push:
    branches:
      - main  # Ganti ke 'master' jika cabang utama di GitHub kamu namanya master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: root # Sesuai dengan user VPS kamu saat ini
        key: ${{ secrets.VPS_SSH_KEY }}
        port: 22 
        script: |
          # 1. Masuk ke folder aplikasi di VPS
          cd /home/administrator/wa-bailey-dev-v2
          
          # 2. Tarik kode terbaru dari GitHub
          git pull origin main
          
          # 3. Install dependencies jika ada library baru (opsional tapi aman)
          npm install --production
          
          # 4. Jalankan script restart PM2 yang ada di package.json kamu
          npm run pm2:restart